# Generated by Django 3.0.10 on 2021-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0005_auto_20201102_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='company_email',
            field=models.CharField(default='info@specterops.io', help_text='Email address to reference in reports', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_name',
            field=models.CharField(default='SpecterOps', help_text='Company name handle to reference in reports', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_twitter',
            field=models.CharField(default='@specterops', help_text='Twitter handle to reference in reports', max_length=255, verbose_name='Twitter Handle'),
        ),
    ]
